version: "3"
services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pramod
      - POSTGRES_PASSWORD=pramu123
      - POSTGRES_DB=railways
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres-data:
